export const SERVER_URL = process.env.REACT_APP_SERVER_URL;
export const DEFAULT_PAGE_SIZE = 10;
export const TABLE_BORDER_COLOR = "#f1f5f1";
export const NO_RECORD = "No Record Found.";
export const USER_TYPE_MANAGER = "event_manager";
export const USER_TYPE_USER = "user";
export const USER_TYPE_ADMIN = "admin";
export const EVENT_TYPE = [ 
  {id:"5f8400979153a0d2b2662693", value:"Appearance or Signing"},
  {id:"5f8400a59074644b32ccffa6", value:"Attraction"},
  {id:"5f8400acfe392d4a6793879f", value:"Camp, Trip, or Retreat"},
  {id:"5f8400b2ab466f494ac1ad4f", value:"Class, Training, or Workshop"},
  {id:"5f8400b8fc94b3891fadbb38", value:"Concert or Performance"},
  {id:"5f8400bf504c0fea4b909e40", value:"Conference"},
  {id:"5f8400c449e289332b6b91e0", value:"Convention"},
  {id:"5f8400c9549738c02b77d136", value:"Dinner or Gala"},
  // {id:"5", value:"Festival or Fair"},
  // {id:"14", value:"Game or Competition"},
  // {id:"10", value:"Meeting or Networking Event"},
  // {id:"100", value:"Other"},
  // {id:"11", value:"Party or Social Gathering"},
  // {id:"15", value:"Race or Endurance Event"},
  // {id:"12", value:"Rally"},
  // {id:"7", value:"Screening"},
  // {id:"2", value:"Seminar or Talk"},
  // {id:"16", value:"Tour"},
  // {id:"13", value:"Tournament"},
  // {id:"3", value:"Tradeshow, Consumer Show, or Expo"}
];

export const EVENT_CATEGORY_TYPE = [ 
  {id:"5f8400f77d390896021e384f", value: "Auto, Boat & Air"},
  {id:"5f8401016a72f919b4992656", value: "Business & Professional"},
  {id:"5f84010859d72f8d790cee13", value: "Charity & Causes"},
  {id:"5f84010e308816e22811bb9e", value: "Community & Culture"},
  {id:"5f840113aa17de6584de72a4", value: "Family & Education"},
  {id:"5f84011960996397661290b5", value: "Fashion & Beauty"},
  {id:"5f84011eb16923dea786c806", value: "Film, Media & Entertainment"},
  {id:"5f840125057e8d862b98fad3", value: "Food & Drink"},
  {id:"5f84012a38a3b5e171c66640", value: "Government & Politics"},
  {id:"5f84012f25d899d89e8b73d5", value: "Health & Wellness"},
  // {id:"119", value: "Hobbies & Special Interest"},
  // {id:"117", value: "Home & Lifestyle"},
  // {id:"103", value: "Music"},
  // {id:"199", value: "Other"},
  // {id:"105", value: "Performing & Visual Arts"},
  // {id:"114", value: "Religion & Spirituality"},
  // {id:"120", value: "School Activities"},
  // {id:"102", value: "Science & Technology"},
  // {id:"116", value: "Seasonal & Holiday"},
  // {id:"108", value: "Sports & Fitness"},
  // {id:"109", value: "Travel & Outdoor"}
];

export const EVENT_SUB_CATEGORY_TYPE = [  
  {id:"5f84014d289e70615456d69e", value:"Adult"},
  {id:"5f8401560d21a557673a172b", value:"Anime"},
  {id:"5f84015b3b530120367e095e", value:"Comedy"},
  {id:"5f8401615613c7f315198022", value:"Comics"},
  {id:"5f8401678e6a365edf35858a", value:"Film"},
  {id:"5f84016d207305afadf64e3e", value:"Gaming"},
  {id:"5f8401734e0721e7715e358d", value:"Other"},
  {id:"4005f840179c5b4dd27d028aa8f1", value:"TV"}
];

export const EVENT_LOCATION = [
  { id: "venue", value: "Venue" },
  { id: "online", value: "Online" },
  { id: "toBeAnnounced", value: "To Be Announced" },
];
export const TICKET_PRICE_INFO = [
  { id: "Free:", value: "Free" },
  { id: "Paid", value: "Paid" },
  { id: "Donation", value: "Donation" },
];
export const TICKET_STATUS = [
  { id: "Active", value: "Active" },
  { id: "Inactive", value: "Inactive" },
];
export const TICKET_SEAT = [
  { id: "Limited", value: "Limited" },
  { id: "Unlimited", value: "Unlimited" },
];
export const TICKET_TAX_WHO_WILL_PAY = [
  {
    id: "You want to pay Payment gateway charge",
    value: "You want to pay  Payment gateway charge",
  },
  {
    id: "User will pay  Payment gateway charge",
    value: "User will pay  Payment gateway charge",
  },
];

export const CURRENCY = [
  { id: "United States Dollars", value: "United States Dollars" },
  { id: "Euro", value: "Euro" },
  { id: "United Kingdom Pounds", value: "United Kingdom Pounds" },
  { id: "Algeria Dinars", value: "Algeria Dinars" },
  { id: "Argentina Pesos", value: "Argentina Pesos" },
  { id: "Australia Dollars", value: "Australia Dollars" },
  { id: "Austria Schillings", value: "Austria Schillings" },
  { id: "Bahamas Dollars", value: "Bahamas Dollars" },
  { id: "Barbados Dollars", value: "Barbados Dollars" },
  { id: "Belgium Francs", value: "Belgium Francs" },
  { id: "Bermuda Dollars", value: "Bermuda Dollars" },
  { id: "Brazil Real", value: "Brazil Real" },
  { id: "Bulgaria Lev", value: "Bulgaria Lev" },
  { id: "Canada Dollars", value: "Canada Dollars" },
  { id: "Chile Pesos", value: "Chile Pesos" },
  { id: "China Yuan Renmimbi", value: "China Yuan Renmimbi" },
  { id: "Cyprus Pounds", value: "Cyprus Pounds" },
  { id: "Czech Republic Koruna", value: "Czech Republic Koruna" },
  { id: "Denmark Kroner", value: "Denmark Kroner" },
  { id: "Dutch Guilders", value: "Dutch Guilders" },
  { id: "Eastern Caribbean Dollars", value: "Eastern Caribbean Dollars" },
  { id: "Egypt Pounds", value: "Egypt Pounds" },
  { id: "Fiji Dollars", value: "Fiji Dollars" },
  { id: "Finland Markka", value: "Finland Markka" },
  { id: "France Francs", value: "France Francs" },
  { id: "Germany Deutsche Marks", value: "Germany Deutsche Marks" },
  { id: "Gold Ounces", value: "Gold Ounces" },
  { id: "Greece Drachmas", value: "Greece Drachmas" },
  { id: "Hong Kong Dollars", value: "Hong Kong Dollars" },
  { id: "Hungary Forint", value: "Hungary Forint" },
  { id: "Iceland Krona", value: "Iceland Krona" },
  { id: "India Rupees", value: "India Rupees" },
  { id: "Indonesia Rupiah", value: "Indonesia Rupiah" },
  { id: "Ireland Punt", value: "Ireland Punt" },
  { id: "Israel New Shekels", value: "Israel New Shekels" },
  { id: "Italy Lira", value: "Italy Lira" },
  { id: "Jamaica Dollars", value: "Jamaica Dollars" },
  { id: "Japan Yen", value: "Japan Yen" },
  { id: "Jordan Dinar", value: "Jordan Dinar" },
  { id: "Korea (South) Won", value: "Korea (South) Won" },
  { id: "Lebanon Pounds", value: "Lebanon Pounds" },
  { id: "Luxembourg Francs", value: "Luxembourg Francs" },
  { id: "Malaysia Ringgit", value: "Malaysia Ringgit" },
  { id: "Mexico Pesos", value: "Mexico Pesos" },
  { id: "Netherlands Guilders", value: "Netherlands Guilders" },
  { id: "New Zealand Dollars", value: "New Zealand Dollars" },
  { id: "Norway Kroner", value: "Norway Kroner" },
  { id: "Pakistan Rupees", value: "Pakistan Rupees" },
  { id: "Palladium Ounces", value: "Palladium Ounces" },
  { id: "Philippines Pesos", value: "Philippines Pesos" },
  { id: "Platinum Ounces", value: "Platinum Ounces" },
  { id: "Poland Zloty", value: "Poland Zloty" },
  { id: "Portugal Escudo", value: "Portugal Escudo" },
  { id: "Romania Leu", value: "Romania Leu" },
  { id: "Russia Rubles", value: "Russia Rubles" },
  { id: "Saudi Arabia Riyal", value: "Saudi Arabia Riyal" },
  { id: "Silver Ounces", value: "Silver Ounces" },
  { id: "Singapore Dollars", value: "Singapore Dollars" },
  { id: "Slovakia Koruna", value: "Slovakia Koruna" },
  { id: "South Africa Rand", value: "South Africa Rand" },
  { id: "South Korea Won", value: "South Korea Won" },
  { id: "Spain Pesetas", value: "Spain Pesetas" },
  { id: "Special Drawing Right (IMF)", value: "Special Drawing Right (IMF)" },
  { id: "Sudan Dinar", value: "Sudan Dinar" },
  { id: "Sweden Krona", value: "Sweden Krona" },
  { id: "Switzerland Francs", value: "Switzerland Francs" },
  { id: "Taiwan Dollars", value: "Taiwan Dollars" },
  { id: "Thailand Baht", value: "Thailand Baht" },
  { id: "Trinidad and Tobago Dollars", value: "Trinidad and Tobago Dollars" },
  { id: "Turkey Lira", value: "Turkey Lira" },
  { id: "Venezuela Bolivar", value: "Venezuela Bolivar" },
  { id: "Zambia Kwacha", value: "Zambia Kwacha" },
  { id: "Eastern Caribbean Dollars", value: "Eastern Caribbean Dollars" },
  { id: "Special Drawing Right (IMF)", value: "Special Drawing Right (IMF)" },
  { id: "Silver Ounces", value: "Silver Ounces" },
  { id: "Gold Ounces", value: "Gold Ounces" },
  { id: "Palladium Ounces", value: "Palladium Ounces" },
  { id: "Platinum Ounces", value: "Platinum Ounces" },
];
export const COUNTRIES = [
  { id: "Afghanistan", value: "Afghanistan" },
  { id: "Albania", value: "Albania" },
  { id: "Algeria", value: "Algeria" },
  { id: "Andorra", value: "Andorra" },
  { id: "Angola", value: "Angola" },
  { id: "Antigua and Barbuda", value: "Antigua and Barbuda	" },
  { id: "Argentina", value: "Argentina" },
  { id: "Armenia", value: "Armenia" },
  { id: "Australia", value: "Australia" },
  { id: "Austria", value: "Austria" },
  { id: "Azerbaijan", value: "Azerbaijan" },
  { id: "Bahamas", value: "Bahamas" },
  { id: "Bahrain", value: "Bahrain" },
  { id: "Bangladesh", value: "Bangladesh" },
  { id: "Barbados", value: "Barbados" },
  { id: "Belarus", value: "Belarus" },
  { id: "Belgium", value: "Belgium" },
  { id: "Belize", value: "Belize" },
  { id: "Benin", value: "Benin" },
  { id: "Bhutan", value: "Bhutan" },
  { id: "Bolivia", value: "Bolivia" },
  { id: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina" },
  { id: "Botswana", value: "Botswana" },
  { id: "Brazil", value: "Brazil" },
  { id: "Brunei", value: "Brunei" },
  { id: "Bulgaria", value: "Bulgaria" },
  { id: "Burkina Faso", value: "Burkina Faso" },
  { id: "Burundi", value: "Burundi" },
  { id: 'Côte d"Ivoire', value: 'Côte d"Ivoire' },
  { id: "Cabo Verde", value: "Cabo Verde" },
  { id: "Cambodia", value: "Cambodia" },
  { id: "Cameroon", value: "Cameroon" },
  { id: "Canada", value: "Canada" },
  { id: "Central African Republic", value: "Central African Republic" },
  { id: "Chad", value: "Chad" },
  { id: "Chile", value: "Chile" },
  { id: "China", value: "China" },
  { id: "Colombia", value: "Colombia" },
  { id: "Comoros", value: "Comoros" },
  { id: "Congo (Congo-Brazzaville)", value: "Congo (Congo-Brazzaville)" },
  { id: "Costa Rica", value: "Costa Rica" },
  { id: "Croatia", value: "Croatia" },
  { id: "Cuba", value: "Cuba" },
  { id: "Cyprus", value: "Cyprus" },
  { id: "Czechia (Czech Republic)", value: "Czechia (Czech Republic)" },
  {
    id: "Democratic Republic of the Congo",
    value: "Democratic Republic of the Congo",
  },
  { id: "Denmark", value: "Denmark" },
  { id: "Djibouti", value: "Djibouti" },
  { id: "Dominica", value: "Dominica" },
  { id: "Dominican Republic", value: "Dominican Republic" },
  { id: "Ecuador", value: "Ecuador" },
  { id: "Egypt", value: "Egypt" },
  { id: "El Salvador", value: "El Salvador" },
  { id: "Equatorial Guinea", value: "Equatorial Guinea" },
  { id: "Eritrea", value: "Eritrea" },
  { id: "Estonia", value: "Estonia" },
  { id: 'Eswatini (fmr. "Swaziland")', value: 'Eswatini (fmr. "Swaziland")' },
  { id: "Ethiopia", value: "Ethiopia" },
  { id: "Fiji", value: "Fiji" },
  { id: "Finland", value: "Finland" },
  { id: "France", value: "France" },
  { id: "Gabon", value: "Gabon" },
  { id: "Gambia", value: "Gambia" },
  { id: "Georgia", value: "Georgia" },
  { id: "Germany", value: "Germany" },
  { id: "Ghana", value: "Ghana" },
  { id: "Greece", value: "Greece" },
  { id: "Grenada", value: "Grenada" },
  { id: "Guatemala", value: "Guatemala" },
  { id: "Guinea", value: "Guinea" },
  { id: "Guinea-Bissau", value: "Guinea-Bissau" },
  { id: "Guyana", value: "Guyana" },
  { id: "Haiti", value: "Haiti" },
  { id: "Holy See", value: "Holy See" },
  { id: "Honduras", value: "Honduras" },
  { id: "Hungary", value: "Hungary" },
  { id: "Iceland", value: "Iceland" },
  { id: "India", value: "India" },
  { id: "Indonesia", value: "Indonesia" },
  { id: "Iran", value: "Iran" },
  { id: "Iraq", value: "Iraq" },
  { id: "Ireland", value: "Ireland" },
  { id: "Israel", value: "Israel" },
  { id: "Italy", value: "Italy" },
  { id: "Jamaica", value: "Jamaica" },
  { id: "Japan", value: "Japan" },
  { id: "Jordan", value: "Jordan" },
  { id: "Kazakhstan", value: "Kazakhstan" },
  { id: "Kenya", value: "Kenya" },
  { id: "Kiribati", value: "Kiribati" },
  { id: "Kuwait", value: "Kuwait" },
  { id: "Kyrgyzstan", value: "Kyrgyzstan" },
  { id: "Laos", value: "Laos" },
  { id: "Latvia", value: "Latvia" },
  { id: "Lebanon", value: "Lebanon" },
  { id: "Lesotho", value: "Lesotho" },
  { id: "Liberia", value: "Liberia" },
  { id: "Libya", value: "Libya" },
  { id: "Liechtenstein", value: "Liechtenstein" },
  { id: "Lithuania", value: "Lithuania" },
  { id: "Luxembourg", value: "Luxembourg" },
  { id: "Madagascar", value: "Madagascar" },
  { id: "Malawi", value: "Malawi" },
  { id: "Malaysia", value: "Malaysia" },
  { id: "Maldives", value: "Maldives" },
  { id: "Mali", value: "Mali" },
  { id: "Malta", value: "Malta" },
  { id: "Marshall Islands", value: "Marshall Islands" },
  { id: "Mauritania", value: "Mauritania" },
  { id: "Mauritius", value: "Mauritius" },
  { id: "Mexico", value: "Mexico" },
  { id: "Micronesia", value: "Micronesia" },
  { id: "Moldova", value: "Moldova" },
  { id: "Monaco", value: "Monaco" },
  { id: "Mongolia", value: "Mongolia" },
  { id: "Montenegro", value: "Montenegro" },
  { id: "Morocco", value: "Morocco" },
  { id: "Mozambique", value: "Mozambique" },
  { id: "Myanmar (formerly Burma)", value: "Myanmar (formerly Burma)" },
  { id: "Namibia", value: "Namibia" },
  { id: "Nauru", value: "Nauru" },
  { id: "Nepal", value: "Nepal" },
  { id: "Netherlands", value: "Netherlands" },
  { id: "New Zealand", value: "New Zealand" },
  { id: "Nicaragua", value: "Nicaragua" },
  { id: "Niger", value: "Niger" },
  { id: "Nigeria", value: "Nigeria" },
  { id: "North Korea", value: "North Korea" },
  { id: "North Macedonia", value: "North Macedonia" },
  { id: "Norway", value: "Norway" },
  { id: "Oman", value: "Oman" },
  { id: "Pakistan", value: "Pakistan" },
  { id: "Palau", value: "Palau" },
  { id: "Palestine State", value: "Palestine State" },
  { id: "Panama", value: "Panama" },
  { id: "Papua New Guinea", value: "Papua New Guinea" },
  { id: "Paraguay", value: "Paraguay" },
  { id: "Peru", value: "Peru" },
  { id: "Philippines", value: "Philippines" },
  { id: "Poland", value: "Poland" },
  { id: "Portugal", value: "Portugal" },
  { id: "Qatar", value: "Qatar" },
  { id: "Romania", value: "Romania" },
  { id: "Russia", value: "Russia" },
  { id: "Rwanda", value: "Rwanda" },
  { id: "Saint Kitts and Nevis", value: "Saint Kitts and Nevis" },
  { id: "Saint Lucia", value: "Saint Lucia" },
  {
    id: "Saint Vincent and the Grenadines",
    value: "Saint Vincent and the Grenadines",
  },
  { id: "Samoa", value: "Samoa" },
  { id: "San Marino", value: "San Marino" },
  { id: "Sao Tome and Principe", value: "Sao Tome and Principe" },
  { id: "Saudi Arabia", value: "Saudi Arabia" },
  { id: "Senegal", value: "Senegal" },
  { id: "Serbia", value: "Serbia" },
  { id: "Seychelles", value: "Seychelles" },
  { id: "Sierra Leone", value: "Sierra Leone" },
  { id: "Singapore", value: "Singapore" },
  { id: "Slovakia", value: "Slovakia" },
  { id: "Slovenia", value: "Slovenia" },
  { id: "Solomon Islands", value: "Solomon Islands" },
  { id: "Somalia", value: "Somalia" },
  { id: "South Africa", value: "South Africa" },
  { id: "South Korea", value: "South Korea" },
  { id: "South Sudan", value: "South Sudan" },
  { id: "Spain", value: "Spain" },
  { id: "Sri Lanka", value: "Sri Lanka" },
  { id: "Sudan", value: "Sudan" },
  { id: "Suriname", value: "Suriname" },
  { id: "Sweden", value: "Sweden" },
  { id: "Switzerland", value: "Switzerland" },
  { id: "Syria", value: "Syria" },
  { id: "Tajikistan", value: "Tajikistan" },
  { id: "Tanzania", value: "Tanzania" },
  { id: "Thailand", value: "Thailand" },
  { id: "Timor-Leste", value: "Timor-Leste	" },
  { id: "Togo", value: "Togo" },
  { id: "Tonga", value: "Tonga" },
  { id: "Trinidad and Tobago", value: "Trinidad and Tobago	" },
  { id: "Tunisia", value: "Tunisia" },
  { id: "Turkey", value: "Turkey" },
  { id: "Turkmenistan", value: "Turkmenistan	" },
  { id: "Tuvalu", value: "Tuvalu" },
  { id: "Uganda", value: "Uganda" },
  { id: "Ukraine", value: "Ukraine" },
  { id: "United Arab Emirates", value: "United Arab Emirates" },
  { id: "United Kingdom", value: "United Kingdom" },
  { id: "United States of America", value: "United States of America" },
  { id: "Uruguay", value: "Uruguay" },
  { id: "Uzbekistan", value: "Uzbekistan" },
  { id: "Vanuatu", value: "Vanuatu" },
  { id: "Venezuela", value: "Venezuela" },
  { id: "Vietnam", value: "Vietnam" },
  { id: "Yemen", value: "Yemen" },
  { id: "Zambia", value: "Zambia" },
  { id: "Zimbabwe", value: "Zimbabwe" },
];

export const EVENT_ORGANIZER = [ 
  { id: "5f83f3ed43d481c1ce820691", value: "Rajveer Singh Rathore" },
  { id: "5f83f61b43d481c1ce820692", value: "Manveer" },
];

export const DATE_FORMATE = "YYYY-MM-DD";
